<?php
/**
 * Persists generated audio in the Media Library.
 *
 * @package TainacanNarrativas
 */

declare(strict_types=1);

namespace TainacanNarrativas\TTS;

use TainacanNarrativas\Logging\Logger;
use TainacanNarrativas\Narrative\Normalizer;
use WP_Error;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Files land in uploads/tainacan-narrativas/YYYY/MM/ through wp_upload_bits()
 * (no user-supplied paths, ever) and become regular attachments with
 * post_parent = 0 — never the item, otherwise Tainacan would list the audio
 * among the item's own attachments and the narrative would feed itself.
 */
final class AudioStorage {

	public const META_FLAG = '_tn_generated_audio';
	public const META_ITEM = '_tn_item_id';
	public const SUBDIR    = 'tainacan-narrativas';

	/**
	 * Stores audio bytes as an attachment.
	 *
	 * @param int    $item_id   Item ID (for naming/meta only).
	 * @param int    $version   Narrative version.
	 * @param string $binary    Audio bytes.
	 * @param string $extension File extension (mp3, wav, ogg).
	 * @param string $mime      Mime type.
	 * @param string $title     Attachment title.
	 * @return int|WP_Error Attachment ID.
	 */
	public static function store( int $item_id, int $version, string $binary, string $extension, string $mime, string $title ) {
		if ( '' === $binary ) {
			return new WP_Error( 'tn_audio_empty', __( 'Áudio vazio.', 'tainacan-narrativas' ) );
		}
		$extension = (string) preg_replace( '/[^a-z0-9]/', '', strtolower( $extension ) );
		$extension = '' !== $extension ? $extension : 'mp3';
		$filename  = sprintf( 'narrativa-item-%d-v%d.%s', $item_id, $version, $extension );

		$filter = static function ( array $dirs ): array {
			$sub            = '/' . self::SUBDIR . '/' . gmdate( 'Y' ) . '/' . gmdate( 'm' );
			$dirs['subdir'] = $sub;
			$dirs['path']   = $dirs['basedir'] . $sub;
			$dirs['url']    = $dirs['baseurl'] . $sub;
			return $dirs;
		};
		add_filter( 'upload_dir', $filter );
		$upload = wp_upload_bits( $filename, null, $binary );
		remove_filter( 'upload_dir', $filter );

		if ( ! empty( $upload['error'] ) || empty( $upload['file'] ) ) {
			Logger::error( 'Audio upload failed', array( 'error' => (string) ( $upload['error'] ?? 'unknown' ) ) );
			return new WP_Error( 'tn_audio_write', __( 'Não foi possível gravar o áudio no diretório de uploads.', 'tainacan-narrativas' ) );
		}

		$attachment_id = wp_insert_attachment(
			array(
				'post_mime_type' => $mime,
				'post_title'     => sanitize_text_field( $title ),
				'post_content'   => '',
				'post_status'    => 'inherit',
				'post_parent'    => 0,
			),
			$upload['file'],
			0,
			true
		);
		if ( is_wp_error( $attachment_id ) || ! $attachment_id ) {
			wp_delete_file( $upload['file'] );
			return is_wp_error( $attachment_id ) ? $attachment_id : new WP_Error( 'tn_audio_attachment', __( 'Falha ao registrar o áudio na biblioteca de mídia.', 'tainacan-narrativas' ) );
		}
		$attachment_id = (int) $attachment_id;

		require_once ABSPATH . 'wp-admin/includes/image.php';
		require_once ABSPATH . 'wp-admin/includes/media.php';
		$meta = wp_generate_attachment_metadata( $attachment_id, $upload['file'] );
		if ( is_array( $meta ) ) {
			wp_update_attachment_metadata( $attachment_id, $meta );
		}
		update_post_meta( $attachment_id, self::META_FLAG, '1' );
		update_post_meta( $attachment_id, self::META_ITEM, $item_id );

		return $attachment_id;
	}

	/**
	 * Duration in seconds: from WP's ID3 metadata, else WAV header, else estimate.
	 *
	 * @param int    $attachment_id Attachment ID.
	 * @param string $script        Script (for the estimate).
	 * @return float
	 */
	public static function duration( int $attachment_id, string $script = '' ): float {
		$meta = wp_get_attachment_metadata( $attachment_id );
		if ( is_array( $meta ) && ! empty( $meta['length'] ) ) {
			return (float) $meta['length'];
		}
		$file = get_attached_file( $attachment_id );
		if ( is_string( $file ) && file_exists( $file ) && 'wav' === strtolower( pathinfo( $file, PATHINFO_EXTENSION ) ) ) {
			$bytes = file_get_contents( $file ); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents -- Local file written by this plugin, not a URL.
			if ( is_string( $bytes ) ) {
				$d = AudioConcat::wav_duration( $bytes );
				if ( $d > 0 ) {
					return $d;
				}
			}
		}
		return Normalizer::estimate_duration( $script );
	}

	/**
	 * Deletes an attachment only if it was generated by this plugin.
	 *
	 * @param int $attachment_id Attachment ID.
	 * @return bool
	 */
	public static function delete( int $attachment_id ): bool {
		if ( $attachment_id <= 0 || '1' !== (string) get_post_meta( $attachment_id, self::META_FLAG, true ) ) {
			return false;
		}
		return (bool) wp_delete_attachment( $attachment_id, true );
	}

	/**
	 * Public URL of the audio (empty when missing).
	 *
	 * @param int $attachment_id Attachment ID.
	 * @return string
	 */
	public static function url( int $attachment_id ): string {
		if ( $attachment_id <= 0 ) {
			return '';
		}
		$url = wp_get_attachment_url( $attachment_id );
		return is_string( $url ) ? $url : '';
	}

	/**
	 * Whether the uploads target is writable (Diagnostics / test-write).
	 *
	 * @return true|WP_Error
	 */
	public static function test_write() {
		$probe = self::store( 0, 0, "RIFF\x24\x00\x00\x00WAVEfmt \x10\x00\x00\x00\x01\x00\x01\x00\x40\x1f\x00\x00\x80\x3e\x00\x00\x02\x00\x10\x00data\x00\x00\x00\x00", 'wav', 'audio/wav', 'tn-write-test' );
		if ( is_wp_error( $probe ) ) {
			return $probe;
		}
		self::delete( (int) $probe );
		return true;
	}
}
